### ISSUE TITLE
Demo raise "AttributeError: 'AsyncChromeDaemon' object has no attribute 'running'"

### ISSUE THREAD

**Issue by bluebad** [ClericPy/ichrome#42]
Python 3.8.8, in virtualenv environ, while I run the demo of ReadMe,
`λ python3 -m ichrome -t
>>> from ichrome.debugger import *
>>> tab = get_a_tab()`
it cry, and the tracebacks:

`Traceback (most recent call last):
  File "K:\python-works\ichrometesting\venv\lib\site-packages\ichrome\debugger.py", line 220, in connect_a_chrome
    return Chrome(host=host, port=port)
  File "K:\python-works\ichrometesting\venv\lib\site-packages\ichrome\debugger.py", line 154, in __init__
    ok = self.run_sync(self._self.connect())
  File "K:\python-works\ichrometesting\venv\lib\site-packages\ichrome\debugger.py", line 54, in run_sync
    return self.loop.run_until_complete(future)
  File "d:\python38\lib\asyncio\base_events.py", line 592, in run_until_complete
    self._check_running()
  File "d:\python38\lib\asyncio\base_events.py", line 552, in _check_running
    raise RuntimeError('This event loop is already running')
RuntimeError: This event loop is already running

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "K:\python-works\ichrometesting\venv\lib\site-packages\ichrome\async_utils.py", line 2085, in repl
    result = eval(code, f_globals, f_locals)
  File "<string>", line 1, in <module>
  File "K:\python-works\ichrometesting\venv\lib\site-packages\ichrome\debugger.py", line 228, in get_a_tab
    chrome = connect_a_chrome(host=host, port=port, **daemon_kwargs)
  File "K:\python-works\ichrometesting\venv\lib\site-packages\ichrome\debugger.py", line 223, in connect_a_chrome
    d = launch(host=host, port=port, **daemon_kwargs)
  File "K:\python-works\ichrometesting\venv\lib\site-packages\ichrome\debugger.py", line 213, in launch
    return Daemon(*args, **kwargs)
  File "K:\python-works\ichrometesting\venv\lib\site-packages\ichrome\debugger.py", line 126, in __init__
    self.run_sync(self._self.__aenter__())
  File "K:\python-works\ichrometesting\venv\lib\site-packages\ichrome\debugger.py", line 54, in run_sync
    return self.loop.run_until_complete(future)
  File "d:\python38\lib\asyncio\base_events.py", line 592, in run_until_complete
    self._check_running()
  File "d:\python38\lib\asyncio\base_events.py", line 552, in _check_running
    raise RuntimeError('This event loop is already running')
RuntimeError: This event loop is already running
Exception ignored in: <function Chrome.__del__ at 0x0000020790AED160>
Traceback (most recent call last):
  File "K:\python-works\ichrometesting\venv\lib\site-packages\ichrome\async_utils.py", line 2450, in __del__
    _exhaust_simple_coro(self.close())
  File "K:\python-works\ichrometesting\venv\lib\site-packages\torequests\_py3_patch.py", line 153, in _exhaust_simple_coro
    coro.send(None)
  File "K:\python-works\ichrometesting\venv\lib\site-packages\ichrome\async_utils.py", line 2443, in close
    if self.req:
  File "K:\python-works\ichrometesting\venv\lib\site-packages\ichrome\async_utils.py", line 2290, in req
    raise ChromeRuntimeError(
ichrome.exceptions.ChromeRuntimeError: please use Chrome in `async with` context
Exception ignored in: <function Daemon.__del__ at 0x0000020790AFFE50>
Traceback (most recent call last):
  File "K:\python-works\ichrometesting\venv\lib\site-packages\ichrome\debugger.py", line 144, in __del__
    self.stop()
  File "K:\python-works\ichrometesting\venv\lib\site-packages\ichrome\debugger.py", line 133, in stop
    if self.running:
  File "K:\python-works\ichrometesting\venv\lib\site-packages\ichrome\debugger.py", line 68, in __getattr__
    value = getattr(self._self, name)
AttributeError: 'AsyncChromeDaemon' object has no attribute 'running'`

**Comment by ClericPy** [comment]
Sorry for that these two lines is forgotten to be removed..

    >>> from ichrome.debugger import *
    >>> tab = get_a_tab()

I am going to update the doc.

**Comment by bluebad** [comment]
> Sorry for that these two lines is forgotten to be removed..
> 
> ```
> >>> from ichrome.debugger import *
> >>> tab = get_a_tab()
> ```
> 
> I am going to update the doc.

Yes, the problem has been solved. Thanks  for the help.
